### PR TITLE
Bug fixed: not mixing up lat/lng, fixed missing polyline

### LINKED ISSUE #218: Bug: Route with charigng stations contains wrong attributes

### PR DESCRIPTION
**Pull request by chrisjherm**
closes #218 
When searching for route including charging stations: Latitude/Longitude not longer mixed up, and the starting point now contains the polyline.

### CODE REVIEW

File: src/backend/src/main/java/com/example/backend/controllers/HereApiRestService.java [hunk 1]
```diff
@@ -67,6 +67,7 @@ public void handleRequest(NlpQueryResponse nlpQueryResponse, List<ApiResult> res
         List<ApiResult> listOfPointsAlongTheRoute = new ArrayList<>();
         try {
             hereRoutingAttributes.setReturnTypeToSummary();
+            hereRoutingAttributes.setReturnTypeToPolylineAndTurnByTurnActions();
```
Comment (oliviadargel) [inline src/backend/src/main/java/com/example/backend/controllers/HereApiRestService.java:70]: Please remove one of the function calls if they're redundant

**Review by oliviadargel — APPROVED** [review]

**Review by oliviadargel — APPROVED** [review]

File: src/backend/src/main/java/com/example/backend/controllers/HereApiRestService.java (hunk 1 above)
Comment (chrisjherm) [reply src/backend/src/main/java/com/example/backend/controllers/HereApiRestService.java:69]: Removed
